# The IBM version of this configuration
version : 0.0.3

# The container name used for the run container
container-name-run : "springclouddemo"

# The container name used for the tools container
container-name-tools : "bx-dev-springclouddemo-tools"

# The name of image to create from dockerfile-run
image-name-run : "springclouddemo"
# The name of image to create from dockerfile-tools
image-name-tools : "bx-dev-java-maven-tools"

# The project root on the host for the run container to mount to container-path-run
host-path-run : "target"

# The command to build the code and docker image for RUN
build-cmd-run : "mvn install -Dmaven.repo.local=/project/.m2/repository"

# The command to execute tests for the code in the tools container
test-cmd : "mvn install -Dmaven.repo.local=/project/.m2/repository"

# The command to build the code and docker image for DEBUG
build-cmd-debug : "mvn install -Dmaven.repo.local=/project/.m2/repository"

# The project root in the run container to mount to host-path-run
container-path-run : "/project"
# The project root in the tools container that will be mounted to host-path-tools
container-path-tools : "/project"

# The port mappings between the host and the container in the form [host:container]
container-port-map : "8080:8080,8443:8443"
# The port mappings between the host and the container for the debug port in the form [host:container]
container-port-map-debug : "8000:8000"

# The command to execute debug of the code in the tools container
debug-cmd : "java -Dspring.profiles.active=local -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=y -jar ./target/<replace-me-with-artifactId-from-pom.xml>-1.0-SNAPSHOT.jar"

# The name for the dockerfile for the run container
dockerfile-run : "Dockerfile"

# The name for the dockerfile for the tools container
dockerfile-tools : "Dockerfile-tools"

# The relative path to the helm chart used for Kubernetes deployment
chart-path : "chart/springclouddemo"
ibm-generated-id : "c99cdd39-f59e-46c8-8f98-1e7c496e1dc9"
ibm-cloud-app-id : "40a13c24-d73d-4684-9b20-c53fdb175df6"
credentials-filepath : "src/main/resources/application-local.properties, src/main/resources/localdev-config.json"

# Deploy to kubernetes cluster
deploy-target: "container"
deploy-image-target: naveenkumarana/spring-demo
ibm-cluster: "mycluster"